sudo: required
dist: bionic

os: linux

language: c

compiler:
  - gcc

addons:
  apt:
    packages:
    - libyajl-dev
    - liblmdb-dev

env:
  - VER_NGINX=1.21.0
  - VER_NGINX=1.20.1
  - VER_NGINX=1.29.8

before_script:
  - cd ..
  - git clone https://github.com/SpiderLabs/ModSecurity.git
  - cd ModSecurity
  - git checkout v3/master
  - git submodule init
  - git submodule update
  - ./build.sh
  - ./configure --without-lmdb
  - make
  - sudo make install
  - cd ..
  - git clone --depth 1 --branch release-${VER_NGINX} https://github.com/nginx/nginx.git
  - cd nginx
  - ./configure --with-http_auth_request_module --with-http_v2_module --add-module=../ModSecurity-nginx
  - make
  - sudo make install
  - cd ..
  - git clone --depth 1 https://github.com/nginx/nginx-tests.git
  - cd nginx-tests
  - cp ../ModSecurity-nginx/tests/* .
  - export TEST_NGINX_BINARY=/usr/local/nginx/sbin/nginx

script:
    - prove .
